# ---------------------------------------------------------------------------
# Computed values used across developer-tier modules
# ---------------------------------------------------------------------------
locals {
  # Must match the names generated by the admin tier for the given database_key
  database_name  = upper("${var.env_prefix}_${var.database_key}")
  warehouse_name = upper("${var.env_prefix}_${var.database_key}_WH")

  # Developer configuration from YAML
  # try() catches yamldecode errors for files that contain only comments / no data
  tables = try(tomap(yamldecode(file("${path.module}/config/tables.yaml"))), {})
  views  = try(tomap(yamldecode(file("${path.module}/config/views.yaml"))), {})

  functions_raw = try(tomap(yamldecode(file("${path.module}/config/functions.yaml"))), {})
  functions = {
    for k, v in local.functions_raw : k => merge(v, {
      body = lookup(v, "body_file", null) != null ? file("${path.module}/../../${v.body_file}") : lookup(v, "body", "")
    })
  }

  tasks_raw = try(tomap(yamldecode(file("${path.module}/config/tasks.yaml"))), {})
  tasks = {
    for k, v in local.tasks_raw : k => merge(v, {
      sql_statement = lookup(v, "sql_file", null) != null ? file("${path.module}/../../${v.sql_file}") : lookup(v, "sql_statement", "")
    })
  }

  procedures_raw = try(tomap(yamldecode(file("${path.module}/config/procedures.yaml"))), {})
  procedures = {
    for k, v in local.procedures_raw : k => merge(v, {
      body = lookup(v, "body_file", null) != null ? file("${path.module}/../../${v.body_file}") : lookup(v, "body", "")
    })
  }
}
